/**
 * 前端可视化技术:
 * 底层图形引擎: Skia, OpenGl...
 * W3C: CSS3, Canvas, SVG, WebGL
 * 第三方库: ZRender, Echarts, AntV, Highcharts, D3.js, Three.js,百度地图, 高德地图...
 * 低代码可视化平台: 阿里云(DataV), 腾讯云图, 网易云图, 网易有数(EasyScreen), 帆软....
 */